from lifesim.utils.direction import Direction


ABSOLUTE_DIRECTION_MAPPING: dict[tuple[Direction, Direction], Direction] = {
    (Direction.UP, Direction.UP): Direction.UP,
    (Direction.UP, Direction.DOWN): Direction.DOWN,
    (Direction.UP, Direction.LEFT): Direction.LEFT,
    (Direction.UP, Direction.RIGHT): Direction.RIGHT,
    (Direction.UP, Direction.UP_LEFT): Direction.UP_LEFT,
    (Direction.UP, Direction.UP_RIGHT): Direction.UP_RIGHT,
    (Direction.UP, Direction.DOWN_LEFT): Direction.DOWN_LEFT,
    (Direction.UP, Direction.DOWN_RIGHT): Direction.DOWN_RIGHT,

    (Direction.DOWN, Direction.UP): Direction.DOWN,
    (Direction.DOWN, Direction.DOWN): Direction.UP,
    (Direction.DOWN, Direction.LEFT): Direction.RIGHT,
    (Direction.DOWN, Direction.RIGHT): Direction.LEFT,
    (Direction.DOWN, Direction.UP_LEFT): Direction.DOWN_RIGHT,
    (Direction.DOWN, Direction.UP_RIGHT): Direction.DOWN_LEFT,
    (Direction.DOWN, Direction.DOWN_LEFT): Direction.UP_RIGHT,
    (Direction.DOWN, Direction.DOWN_RIGHT): Direction.UP_LEFT,

    (Direction.LEFT, Direction.UP): Direction.LEFT,
    (Direction.LEFT, Direction.DOWN): Direction.RIGHT,
    (Direction.LEFT, Direction.LEFT): Direction.DOWN,
    (Direction.LEFT, Direction.RIGHT): Direction.UP,
    (Direction.LEFT, Direction.UP_LEFT): Direction.DOWN_LEFT,
    (Direction.LEFT, Direction.UP_RIGHT): Direction.UP_LEFT,
    (Direction.LEFT, Direction.DOWN_LEFT): Direction.DOWN_RIGHT,
    (Direction.LEFT, Direction.DOWN_RIGHT): Direction.UP_RIGHT,

    (Direction.RIGHT, Direction.UP): Direction.RIGHT,
    (Direction.RIGHT, Direction.DOWN): Direction.LEFT,
    (Direction.RIGHT, Direction.LEFT): Direction.UP,
    (Direction.RIGHT, Direction.RIGHT): Direction.DOWN,
    (Direction.RIGHT, Direction.UP_LEFT): Direction.UP_RIGHT,
    (Direction.RIGHT, Direction.UP_RIGHT): Direction.DOWN_RIGHT,
    (Direction.RIGHT, Direction.DOWN_LEFT): Direction.UP_LEFT,
    (Direction.RIGHT, Direction.DOWN_RIGHT): Direction.DOWN_LEFT,

    (Direction.UP_LEFT, Direction.UP): Direction.UP_LEFT,
    (Direction.UP_LEFT, Direction.DOWN): Direction.DOWN_RIGHT,
    (Direction.UP_LEFT, Direction.LEFT): Direction.DOWN_LEFT,
    (Direction.UP_LEFT, Direction.RIGHT): Direction.UP_RIGHT,
    (Direction.UP_LEFT, Direction.UP_LEFT): Direction.LEFT,
    (Direction.UP_LEFT, Direction.UP_RIGHT): Direction.UP,
    (Direction.UP_LEFT, Direction.DOWN_LEFT): Direction.DOWN,
    (Direction.UP_LEFT, Direction.DOWN_RIGHT): Direction.RIGHT,

    (Direction.UP_RIGHT, Direction.UP): Direction.UP_RIGHT,
    (Direction.UP_RIGHT, Direction.DOWN): Direction.DOWN_LEFT,
    (Direction.UP_RIGHT, Direction.LEFT): Direction.UP_LEFT,
    (Direction.UP_RIGHT, Direction.RIGHT): Direction.DOWN_RIGHT,
    (Direction.UP_RIGHT, Direction.UP_LEFT): Direction.UP,
    (Direction.UP_RIGHT, Direction.UP_RIGHT): Direction.RIGHT,
    (Direction.UP_RIGHT, Direction.DOWN_LEFT): Direction.LEFT,
    (Direction.UP_RIGHT, Direction.DOWN_RIGHT): Direction.DOWN,

    (Direction.DOWN_LEFT, Direction.UP): Direction.DOWN_LEFT,
    (Direction.DOWN_LEFT, Direction.DOWN): Direction.UP_RIGHT,
    (Direction.DOWN_LEFT, Direction.LEFT): Direction.DOWN_RIGHT,
    (Direction.DOWN_LEFT, Direction.RIGHT): Direction.UP_LEFT,
    (Direction.DOWN_LEFT, Direction.UP_LEFT): Direction.DOWN,
    (Direction.DOWN_LEFT, Direction.UP_RIGHT): Direction.LEFT,
    (Direction.DOWN_LEFT, Direction.DOWN_LEFT): Direction.RIGHT,
    (Direction.DOWN_LEFT, Direction.DOWN_RIGHT): Direction.UP,

    (Direction.DOWN_RIGHT, Direction.UP): Direction.DOWN_RIGHT,
    (Direction.DOWN_RIGHT, Direction.DOWN): Direction.UP_LEFT,
    (Direction.DOWN_RIGHT, Direction.LEFT): Direction.UP_RIGHT,
    (Direction.DOWN_RIGHT, Direction.RIGHT): Direction.DOWN_LEFT,
    (Direction.DOWN_RIGHT, Direction.UP_LEFT): Direction.RIGHT,
    (Direction.DOWN_RIGHT, Direction.UP_RIGHT): Direction.DOWN,
    (Direction.DOWN_RIGHT, Direction.DOWN_LEFT): Direction.UP,
    (Direction.DOWN_RIGHT, Direction.DOWN_RIGHT): Direction.LEFT
}